version: "3"

services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    environment: {}
    volumes:
      - /data
    expose:
      - 6379
    command: ["--appendonly", "yes"]

  api:
    container_name: api
    build: .
    restart: always
    env_file: .env.sample
    ports:
        - 8000:8000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./.tmp:/app/.tmp
    depends_on:
        - redis
