version: "3"

services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    environment: {}
    volumes:
      - /data
    expose:
      - 6379
    command: ["--appendonly", "yes"]

  tx-persistence:
    container_name: tx-persistence
    image: txscience/tx-persistence
    restart: always
    env_file:
      - .env
    expose:
      - 27017
      - 27018
      - 27019

  api:
    container_name: api
    build: .
    restart: always
    env_file: .env
    ports:
        - 8000:8000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data:/app/data
    depends_on:
        - redis
        - tx-persistence
